### ISSUE TITLE
spring cloud config 설정 추가 (server / client)

### ISSUE THREAD

**Issue by writer0713** [writer0713/msa-practice#31]
# 참고
- 아래 이유로 다른 강좌 보면서 진행
  - 낮은 버전의 spring cloud config 로 설명 진행
  - git repository 사용시 user / password 사용하라고함
- 참고한 강좌
  - https://youtu.be/2EVLFqleV7w?list=PLJkjrxxiBSFBPk-6huuqcjiOal1KdU88R
  - https://youtu.be/qeQPBImEGec?list=PLJkjrxxiBSFBPk-6huuqcjiOal1KdU88R
  - https://youtu.be/EQ31GAYxqSk?list=PLJkjrxxiBSFBPk-6huuqcjiOal1KdU88R
- [git config - private repo](https://github.com/writer0713/msa-practice-config)
- git private key 사용하는 방법 고민
  - 여러가지 시도 해봤지만 실패
  - 아래 방법으로 성공
    - `private.yml` 파일 생성하고 내부에 git private key 등록
      - ![Image](https://github.com/user-attachments/assets/74d21cfe-a5bd-471f-b3f5-9552fd4513c9)
      - ![Image](https://github.com/user-attachments/assets/d61a6d34-c278-405b-b5f6-1cec076b86ac)
    - `.gitignore` 에 `private.yml` 등록해서 git 에 올라가지 않도록 설정
    - `application.yml` 에서 아래와 같이 사용
```yml
spring:
  config:
    import:
      - private.yml
  cloud:
    config:
      server:
        git:
          uri: git@github.com:writer0713/msa-practice-config.git
          ignoreLocalSshSettings: true
          private-key: ${git.private-key}
```
- actuator refresh 실행시, 
  - `Environment` 객체 사용해서 `env.getProperty("xxx")` 와 같이 사용하면 바뀐 값을 사용 가능
  - 아래 코드와 같이 `@Component` 에서 `@Value` 를 통해 객체로 만들어 놓은 것은 refresh 안됨
```kt
@Component
data class Greeting(
    @Value("\${greeting.message}")
    val message: String,
)
```

![Image](https://github.com/user-attachments/assets/ebc83440-2a2b-4af1-a50d-3ec77c88f8bd)

![Image](https://github.com/user-attachments/assets/cfbf8768-94fa-4bbd-8417-6937b691cdce)
